// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDECVMGz33weXU52bUU7Tp31Hgrg3Nu3iU',
    appId: '1:666159939154:web:e847903b3057fa6220a98b',
    messagingSenderId: '666159939154',
    projectId: 'devdynasty-bitnbuild',
    authDomain: 'devdynasty-bitnbuild.firebaseapp.com',
    storageBucket: 'devdynasty-bitnbuild.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjEWYwrErjALRIZGdVcGIro3IU4Cw6pKU',
    appId: '1:666159939154:android:842648245cb71d0a20a98b',
    messagingSenderId: '666159939154',
    projectId: 'devdynasty-bitnbuild',
    storageBucket: 'devdynasty-bitnbuild.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDCss7evbFY-ic0AyvR8gIVXiivbCyWL0',
    appId: '1:666159939154:ios:4df53004380b39e820a98b',
    messagingSenderId: '666159939154',
    projectId: 'devdynasty-bitnbuild',
    storageBucket: 'devdynasty-bitnbuild.appspot.com',
    iosBundleId: 'com.example.whistleitApp',
  );
}
